import os
os.chdir('taxi-dermistes-core')
os.system('npm install tracer --save')
os.system('npm install express --save')
os.system('npm install body-parser --save')
os.system('npm install validator --save')
os.system('npm install eslint --save-dev')
os.system('npm install eslint-config-usecases --save-dev')
os.system('npm install browserify --save-dev')
os.system('npm install jquery --save-dev')
os.system('npm install bluebird --save-dev')

os.chdir('../taxi-dermistes-web')
os.system('npm install express-http-proxy --save')
os.system('npm install express --save')
os.system('npm install eslint --save-dev')
os.system('npm install eslint-config-usecases --save-dev')
os.system('npm install browserify --save-dev')
os.system('npm install morgan --save')
os.system('npm install jquery --save')
os.system('npm install validator --save')
os.system('npm install nodemon --save-dev')

